---
- name: Setup nodejs12.x
  shell: curl -sL https://rpm.nodesource.com/setup_12.x | sudo -E bash -

- name: Installing latest version of node.js
  become: yes
  yum:
    name: nodejs
    state: latest
    lock_timeout: 180

- name: Install yarn package
  get_url:
    url: https://dl.yarnpkg.com/rpm/yarn.repo
    dest: /etc/yum.repos.d/yarn.repo

- name: Installing yarn
  yum:
    name: yarn
    state: latest

- name: Execute yarn 
  become: yes
  shell: yarn install --check-files